### ISSUE TITLE
MQE Demo and File Upload won't run on Mac

### ISSUE THREAD

**Issue by michellefbarber** [immregistries/mqe#103] opened 2018-08-13 19:26 UTC
[OVERVIEW]
HL7 message is generated, submit button won't return a result on Mac. Tested on Windows 7 and it works.

2018-08-13 13:19:12.958 ERROR 24288 --- [nio-8756-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/ws/BindingProvider] with root cause

Similarly, File Upload feature does not appear to work:

2018-08-13 13:23:23.495 ERROR 24288 --- [nio-8756-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.springframework.web.accept.PathExtensionContentNegotiationStrategy$JafMediaTypeFactory] with root cause

2018-08-13 13:23:26.504 ERROR 24288 --- [nio-8756-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/ws/BindingProvider] with root cause

![screen shot 2018-08-13 at 1 28 49 pm](https://user-images.githubusercontent.com/33353164/44053447-e89a548e-9efc-11e8-9d07-79e4c64b0a3c.png)

Mac OS High Sierra - 10.13.6 (17G65)
Browsers Tested: 
Google Chrome - 68.0.3440.106 (Official Build) (64-bit)
Safari - 11.1.2 (13605.3.8)
Firefox Quantum - 61.0.2 (64-bit)

[Also discovered an issue with the start.command file that failed because line terminators are different on Mac vs PC. Possible that this is related?]

**Comment by oktobershawn** [comment] 2019-02-15 16:16
Unable to reproduce in multiple configurations, closing issue.

**Closed** 2019-02-15 16:16 UTC
Labels: bug
