### ISSUE TITLE
Make Vaccine Codes configurable with XML

### ISSUE THREAD

**Issue by nathanbunker** [immregistries/mqe#68] opened 2018-05-25 11:54 UTC
The Vaccine Code section is currently operated by two enums that embed the concepts of vaccine groups and age groups. This should be something that can be edited and updated by the user. So an XML process should be created to operate this. 

The steps are:
* Generate DTD
* Generate code to read XML
* Change code to read it
* Have report show expectations
* Put Excel spreadsheet on website and indicate how to edit

A separate ticket should be created to allow this XML to be edited in MQE settings page.

**Comment by michellefbarber** [comment] 2018-06-22 17:38
@nathanbunker and @JoshHull - is this something that you two are starting to tackle now?

**Comment by michellefbarber** [comment] 2018-07-09 18:41
Issue #73 was redundant and has been removed

Create a process for keeping code base up-to-date with latest CDC codes and a communication process to release changes. Documentation on process should be visible so that the entire community can understand the steps.

**Comment by michellefbarber** [comment] 2018-07-09 18:55
Duplicate of #74 Need to create XML structure that indicates which vaccinations should be given to which patients in which years.

**Comment by jnarine** [comment] 2018-07-20 17:38
Looks good to me!

**Closed** 2018-07-20 17:38 UTC
Labels: enhancement
